import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/themeProvider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
const font = Nunito({ subsets: ["latin"] });
import { ExitModal } from "@/components/exit-modal";

export const metadata: Metadata = {
  title: "Fluentify ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      variables: {
        fontSize: '0.875rem',
        borderRadius: '0.5rem',
        colorPrimary: 'hsl(142, 71%, 45%)',
      },
    }}>
      <html lang="en">
        <body className={font.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <Toaster/>
              <ExitModal/>
              {children}
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
